spring:      
  logging :
    level:
     org:
      hidernate:
       SQL : DEBUG
       orm :
        jdbc :
         bind : TRACE
       type :
        descriptorsql : TRACE
       springframework :
        orm :
         jpa : DEBUG
        boot :
          autoconfigure :
           orm :
            jpa : DEBUG
       flywaydb : DEBUG